"""Add syllabus_topics table

Revision ID: 7061cf8e77c8
Revises: b254e16f5d46
Create Date: 2025-12-23 20:50:13.020427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7061cf8e77c8'
down_revision = 'b254e16f5d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
