"""Add resource and resource_request tables

Revision ID: c72b13bd3936
Revises: dbffa4e86819
Create Date: 2025-12-23 16:42:08.183273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72b13bd3936'
down_revision = 'dbffa4e86819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
