"""add_profile_image_fixed

Revision ID: dbffa4e86819
Revises: 
Create Date: 2025-12-22 22:42:21.474266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbffa4e86819'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
